### PR TITLE
feat: add base url as parameter

### PR DESCRIPTION
**Pull request by BlackDark**
Waiting for https://github.com/gagoar/github-app-installation-token/pull/124

### CODE REVIEW

**Comment by gagoar** [comment]
Hey @BlackDark I think now we are ready for this!

**Comment by BlackDark** [comment]
> Hey @BlackDark I think now we are ready for this!

Hey @gagoar rebased PR and should be good to go.
@jnwng feel free to review + merge :)

**Review by gagoar — APPROVED** [review]

**Comment by gagoar** [comment]
The steps are failing because the tokens used in this Repo can't be accessed by you. I will cherry pick your commits and recreate the PR in the base repository.

**Comment by gagoar** [comment]
Can you fix the tests ? these should pass in here for you @BlackDark

**Comment by BlackDark** [comment]
> Can you fix the tests ? these should pass in here for you @BlackDark

Done was a problem with the mocked input

**Pull request merged**
